name: Bust Cache
on:
  workflow_dispatch

jobs:

  # https://github.com/actions/cache/issues/2#issuecomment-1098723830
  flush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: /tmp/flush
          key: ${{ github.run_id }}-${{ github.run_attempt }}
      - run: dd if=/dev/random of=/tmp/flush bs=1M count=10000
