name: Publish Tag
on:
  push:
    tags:
      - '*@v*.*.*'

jobs:
  publish-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }} >>
          ~/.npmrc

      - run: ./common/scripts/publish.mjs ${{ github.ref_name }} ${{ github.sha }}
