name: Test
on:
  push:
    branches-ignore:
      - gh-pages
jobs:
  first:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - name: foo
            ext: txt
          - name: bar
            ext: json
          - extra: true
          - depth:
              yes: 123
          - arr:
              - 1
              - 2
          - arr:
              - a: 1
              - b: 2
    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "THIS HAS SOME DATA IN A FILE NAMED ${{ matrix.file.name }}" > ${{ matrix.file.name }}.${{ matrix.file.ext }}

          echo "Can I access data with depth? ${{ matrix.file.depth }}"

      - id: my-step
        run: |
          echo "::set-output name=action_fruit::strawberry"

      - id: outputs-echo-file
        run: $(./outputs.sh)

      - id: outputs-raw-file
        run: $(./other-outputs.sh)

