name: Test
on:
  pull_request:
    type:
      - opened
      - synchronize
      - reopened
  push:
    branches-ignore:
      - gh-pages
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          echo HEAD === $(git rev-parse HEAD)

          echo GITHUB CONTEXT === "${{ toJSON(github) }}"
