name: Test
on:
  pull_request:
    type:
      - opened
      - synchronize
      - reopened
  push:
    branches-ignore:
      - gh-pages
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        depth: 0

      - run: |
          echo HEAD === $(git rev-parse HEAD)

          echo LOG = $(git log)

          git fetch --depth=9999

          echo FETCHED LOG = $(git log)

          echo GITHUB CONTEXT === "${{ toJSON(github) }}"
